'''
Helper script for analysing the tuned model reports generated by tuneAllen.py
'''
import os
import shutil

import json

dirs = os.listdir('.')

for dir in dirs:
    if 'NT_' in dir:
        rep = '%s/report.json'%dir
        if os.path.isfile(rep):
            to = 'reports/%s__report.json'%dir
            print("Copying %s to %s"%(rep,to))
            shutil.copyfile(rep,to)
            

reports = {}

for rep in os.listdir('reports'):
    
    if rep.endswith('json'):
        f = "reports/%s"%rep
        print("Loading in: %s"%f)
        s = open(f, 'r').read()
        reports[rep] = eval(s)
print("\n*********************************\n")
for r in reports:
    rep = reports[r]
    ptype = rep['Prototype'] if rep['Prototype']!='Izhikevich' else 'Izh'
    print("%s:\t%s %s\t %s(p%s)\t%s"%(r,ptype,rep['dataset'],rep['max_evaluations'],rep['population_size'],rep['fitness']))

      
