name: Continuous builds

on:
  push:
    branches: [ master, development, experimental, pg*, add* ]
  pull_request:
    branches: [ master, development, experimental, pg*, add* ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ 3.8 ]
        engine: ["NEURON:8.1.0", "NEURON:7.8.2", "PyNEURON:8.1.0", "PyNEURON:7.8.2", "jNeuroML", "jNeuroML_NEURON", "jNeuroML_NetPyNE", "jNeuroML_validate"]


    steps:
    - uses: actions/checkout@v2

    - name: Set up Python  ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version:  ${{ matrix.python-version }}

    - name: Install OMV
      run: |
        pip install git+https://github.com/OpenSourceBrain/osb-model-validation
        pip install scipy sympy matplotlib cython pandas tables

    - name: Download selected NEURON models
      run: |
         pip install allensdk # for NEURON models
         cd CellTypesDatabase/models
         pip install markupsafe==2.0.1
         python download.py # NWB files here are required for tests
         ls -alt 4*

    - name: Run OMV tests
      run: |
        omv all_ -V

    - name: Print final OMV/engine version info
      run: |
        omv list -V # list installed engines
